query accountInfo($id: ID!) {
	User(id: $id) {
		id
		email
		username
		prefect
		prefectStudents {
			id
			firstname
			surname
		}
		teachesSubjects {
			id
			name
			isPublished
			# tutorLevel {
			# 	levels
			# }
		}
	}
}
