mutation LoginMutation($username: String!, $password: String!) {
  # /server/src/authenticate.graphql: authenticateUser
  authenticateUser(
    username: $username,
    password: $password
  ) {
    token
  }
}
