query allSubjects {
  allSubjects {
    id
    name
    slug
    description
    levelDescriptions
    levels
    area {
      id
      name
      slug
    }
    teachers {
      id
      username
      firstname
      surname
    }
    students {
      id
      firstname
      surname
    }
    tutorLevels {
      id
      teacher {
        id
      }
      subject {
        id
      }
      levels
    }
    competences {
      name
      slug
      id
    }
    projects(
      filter: {
        isPublished: true
      }
    ) {
      id
      name
      slug
      description
      levels
      isPublished
      selfLearn
      materials {
        id
        name
        description
        contentType
        uploadUrl
        linkUrl
        project {
          id
          slug
        }
      }
    }
  }
}
