query userStudentById($id: ID!) {
  User(id: $id) {
    id
    username
    firstname
    surname
    avatar
    avatarColor
    studiesSubjects {
      id
      name
      slug
      levels
      competences {
        id
        name
        slug
      }
      evaluations(
        filter: {
          student: {
            id: $id
          }
        }) {
          id
          level
          value
          competence {
            id
            name
            slug
            subject {
              slug #clean up later?
            }
          }
          student {
            id
            username
          }
      }
    }
    studiesProjects(
      filter: {
        isPublished: true
      }
    ) {
      id
      name
      slug
      level
      selfLearn
      subject {
        id
        slug
      }
    }
    studentLevels {
      level
      subject {
        id
        slug
        name
      }
    }
    selfEvaluations {
      updatedAt
      subject {
        id
        slug
        name
      }
    }
  }
}
