mutation LoginMutation($email: String!, $password: String!) {
  # /server/src/authenticate.graphql: authenticateUser
  authenticateUser(
    email: $email,
    password: $password
  ) {
    token
  }
}
