mutation removeFromTeacherSubject($subjectId: ID!, $teacherId: ID!) {
  removeFromTeacherSubject(
    teachesSubjectsSubjectId: $subjectId
    teachersUserId: $teacherId
  ) {
    teachersUser {
      id
    }
    teachesSubjectsSubject {
      name
    }
  }
}
