mutation createTutorLevels($teacherId: ID!, $subjectId: ID!, $levels: [Levels!]!) {
	createTutorLevels(
		teacherId: $teacherId
		subjectId: $subjectId
		levels: $levels
	) {
		id
		teacher {
			id
			username
		}
		subject {
			id
			name
		}
	}
}
