#import "./ProjectFragment.gql"

mutation projectEdit ($id: ID!, $name: String!, $slug: String!, $description: String!, $selfLearn: Boolean!, $isPublished: Boolean!, $levels: [Levels!]!) {
  updateProject(
    id: $id
    name: $name
    slug: $slug
    description: $description
    selfLearn: $selfLearn
    isPublished: $isPublished
    levels: $levels
  ) {
    ...Project
  }
}
