query allSubjects {
  allSubjects {
    id
    name
    slug
    description
    levels
    area {
      id
      name
      slug
    }
    teachers {
      id
      username
      firstname
      surname
    }
    students {
      id
      firstname
      surname
    }
    tutorLevels {
      id
      teacher {
        id
      }
      subject {
        id
      }
      levels
    }
    competences {
      name
      slug
    }
    projects {
      id
      name
      slug
      description
      level
    }
  }
}
