query allSubjects {
  allSubjects {
    id
    name
    slug
    description
    area {
      id
      name
      slug
    }
    projects {
      id
      name
      slug
    }
    teachers {
      id
      username
    }
    students {
      id
      firstname
      surname
    }
    tutorLevels {
      id
      teacher {
        id
      }
      subject {
        id
      }
      levels
    }
  }
}
