query userStudentById($id: ID!) {
  User(id: $id) {
    id
    username
    firstname
    surname
    avatar
    avatarColor
    studiesSubjects {
      id
      name
      slug
      levels
      evaluations(
        filter: {
          student: {
            id: $id
          }
        }) {
          id
          level
          value
          competence {
            id
            name
            slug
            subject {
              slug #clean up later?
            }
          }
      }
    }
    studiesProjects {
      id
      name
      slug
      subject {
        id
        slug
      }
    }
    studentLevels {
      level
      subject {
        id
        slug
        name
      }
    }
  }
}
