fragment Project on Project {
  id
  name
  slug
  description
  selfLearn
  level
  subject {
    id
  }
  materials {
    id
    name
    description
    contentType
    uploadUrl
    linkUrl
  }
}
