#import "./UserFragment.gql"

mutation userAdd ($username: String!, $email: String!, $password: String!, $firstname: String, $surname: String, $userType: UserTypes) {
  createUser(username: $username, email: $email, password: $password, firstname: $firstname, surname: $surname, userType: $userType) {
    ...User
  }
}
